version: '3'
services:
  fastapi.local:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - sharednet
    volumes:
      - ./backend/main.py:/app/main.py
      - ./backend/.env:/app/.env
    depends_on:
      - mongo.local
  mongo.local:
    image: mongo
    container_name: web-stack-mongo.local
    networks:
      - sharednet
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js
  dashboard.local:
    build:
      context: ./dashboard
    ports:
      - "8080:80"
    networks:
      - sharednet
    volumes:
      - ./dashboard/index.html:/usr/share/nginx/html/index.html
      - ./dashboard/script.js:/usr/share/nginx/html/script.js

networks:
  sharednet: