version: '3'
services:
  fastapi.local:
    build:
      context: ./backend
    networks:
      - sharednet
    volumes:
      #- ./backend/main.py:/app/main.py
      - ./backend/:/app/
    depends_on:
      - mongo.local
  mongo.local:
    image: mongo
    container_name: web-stack-mongo.local
    networks:
      - sharednet
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js
  proxy-dashboard.local:
    build:
      context: ./proxy-dashboard
    ports:
      - "8080:80"
    networks:
      - sharednet
    volumes:
      - ./proxy-dashboard/index.html:/usr/share/nginx/html/index.html
      - ./proxy-dashboard/script.js:/usr/share/nginx/html/script.js

networks:
  sharednet: